name: revali_annotations
description: The base annotations for API generation using Revali
version: 2.0.2-dev
repository: https://github.com/mrgnhnt96/revali/tree/main/packages/revali_annotations
issue_tracker: https://github.com/mrgnhnt96/revali/issues
documentation: https://revali.dev
funding:
    - https://github.com/sponsors/mrgnhnt96
topics:
    - revali
    - api
    - backend
    - server
    - annotation

environment:
    sdk: '>=3.2.6 <4.0.0'

dependencies:
    meta: ^1.15.0
