name: revali_server_custom_params_test
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

resolution: workspace

dependencies:
  revali_router:

dev_dependencies:
  revali:
  revali_server:
  revali_test:
  test: ^1.25.15
