name: revali_client_default_params_test
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

resolution: workspace

dependencies:
  equatable: ^2.0.7
  revali_client:
  revali_client_default_params:
    path: .revali/revali_client
  revali_router:

dev_dependencies:
  revali:
  revali_client_gen:
  revali_client_test:
  revali_server:
  revali_test:
  test: ^1.25.15
