name: revali_client_test
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  async: ^2.13.0
  http: ^1.3.0
  revali_client:
    path: ../revali_client
  revali_test:
    path: ../../../packages/revali_test
  stream_channel: ^2.1.4
  web_socket_channel: ^3.0.2
