name: revali
description: Revali is a build system for creating scalable and efficient APIs with Dart
version: 2.0.4
repository: https://github.com/mrgnhnt96/revali/tree/main/packages/revali
issue_tracker: https://github.com/mrgnhnt96/revali/issues
documentation: https://revali.dev
funding:
  - https://github.com/sponsors/mrgnhnt96
topics:
  - revali
  - api
  - backend
  - server
  - code-generation

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  analyzer: ^8.0.0
  args: ^2.6.0
  async: ^2.12.0
  code_builder: ^4.11.0
  collection: ^1.19.1
  dart_style: ^3.1.2
  equatable: ^2.0.5
  file: ^7.0.1
  glob: ^2.1.3
  json_annotation: ^4.9.0
  mason_logger: ^0.3.1
  path: ^1.9.1
  platform: ^3.1.6
  revali_annotations: ^2.0.2
  revali_construct: ^2.0.3
  revali_core: ^1.4.0
  stack_trace: ^1.12.0
  stream_transform: ^2.1.0
  watcher: ^1.1.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.8.0
  json_serializable: ^6.11.1
  test: ^1.25.8
  very_good_analysis: ^6.0.0

executables:
  revali:
