name: revali_router
description: Feature rich http router for Revali
version: 3.0.0-dev
repository: https://github.com/mrgnhnt96/revali/tree/main/revali_router/revali_router
issue_tracker: https://github.com/mrgnhnt96/revali/issues
documentation: https://revali.dev
funding:
    - https://github.com/sponsors/mrgnhnt96
topics:
    - revali
    - api
    - backend
    - server
    - router

environment:
    sdk: '>=3.2.6 <4.0.0'

dependencies:
    autoequal: ^0.9.1
    collection: ^1.19.0
    copy_with_extension: ^5.0.4
    equatable: ^2.0.5
    file: ^7.0.1
    http_parser: ^4.1.0
    meta: ^1.16.0
    mime: ^1.0.5
    path: ^1.9.0
    revali_annotations: ^1.4.1
    revali_core: ^1.4.0
    revali_router_annotations: ^2.0.0-dev
    revali_router_core: ^2.0.0-dev
    stack_trace: ^1.11.1

dev_dependencies:
    autoequal_gen: ^0.9.1
    build_runner: ^2.4.11
    copy_with_extension_gen: ^5.0.4
    mocktail: ^1.0.4
    test: ^1.25.7
