name: revali_router_core
description: Shared classes between revali_router and revali_router_annotations
version: 2.0.3+1
repository: https://github.com/mrgnhnt96/revali/tree/main/revali_router/revali_router_core
issue_tracker: https://github.com/mrgnhnt96/revali/issues
documentation: https://revali.dev
funding:
  - https://github.com/sponsors/mrgnhnt96
topics:
  - revali
  - api
  - backend
  - server
  - router

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  equatable: ^2.0.5
  http_parser: ^4.1.0
  meta: ^1.16.0
  mime: ^1.0.5
  revali_annotations: ^2.0.2
  revali_core: ^1.4.0

dev_dependencies:
  test: ^1.25.8
